### ISSUE TITLE
Feature Request - Decompress compressed responses

### ISSUE THREAD

**Issue by schabou** [keathley/finch#129]
I wasn't able to find any reference to it in the code or docs so apologies if this is mentioned somewhere or already implemented.

I've run into an issue where an API is returning compressed responses (gzip in this instance) and it caused my client to fail.  I was able to repair this with a stop gap measure on my end but it would be ideal if the Finch library was able to handle decompression seamlessly.

Thanks in advance for your consideration!

**Comment by wojtekmach** [comment]
FWIW neither httpc nor hackney (https://github.com/benoitc/hackney/issues/155) automatically decompressed the response body.

Shameless plug: I'm building an http client where automatic decompression based on the `content-encoding` header is one of the features: http://wojtekmach.pl/docs/req/Req.html. It's still a work-in-progress so I definitely do not recommend using it for anything serious. I've used [Mint guide on decompression](https://hexdocs.pm/mint/decompression.html) which you might find helpful if you decide to implement it in your own project.

**Comment by keathley** [comment]
@schabou Thanks for opening this. I think atm. my suggestion would be to check out Req as @wojtekmach mentioned. We're going to try to keep finch pretty small so it can be re-used for a lot of other use cases. I appreciate that this puts more onus on the users of finch to build these things in their own code. We can talk about revisiting features like this in the future if Req or a similar solution doesn't work out.

Thanks.
