### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by lukas-at-harren** [keathley/finch#130]
I have this request: `curl http://www.kakadu.de/podcast-kakadu.2730.de.podcast.xml`.
The server returns a well formed HTTP response, however, Finch does not return an UTF-8 body, instead, it returns a binary.

```
{:ok,
 [
   {"vary", "Accept-Encoding"},
   {"cache-control", "public, max-age=900, pre-check=900, no-transform"},
   {"x-cache", "HIT"},
   {"content-type", "application/xml; charset=utf-8"},
   {"content-encoding", "gzip"},
   {"p3p", "CP=\"NOI NID ADMa OUR IND UNI COM NAV\""},
   {"date", "Tue, 06 Apr 2021 05:10:07 GMT"},
   {"x-server", "webr03"},
   {"expires", "Tue, 06 Apr 2021 05:25:08 GMT"},
   {"pragma", ""},
   {"accept-ranges", "bytes"},
   {"connection", "Keep-Alive"},
   {"last-modified", "Tue, 06 Apr 2021 05:10:09 GMT"},
   {"x-cache-info", "cached"},
   {"age", "930"},
   {"content-length", "32982"}
 ],
 <<31, 139, 8, 0, 0, 0, 0, 0, 0, 3, 237, 189, 91, 115, 219, 72, 182, 38, 250,
   222, 191, 2, 229, 29, 177, 199, 221, 35, 136, 184, 95, 84, 213, 229, 35, 149,
   175, 37, 203, 246, 182, 236, 242, 236, 154, 152, 96, ...>>}
```

I would have expected something along those lines (taken from curl):

```
< HTTP/1.1 200 OK
< Cache-Control: public, max-age=900, pre-check=900, no-transform
< X-Cache: HIT
< Content-Type: application/xml; charset=utf-8
< P3P: CP="NOI NID ADMa OUR IND UNI COM NAV"
< Date: Tue, 06 Apr 2021 05:33:44 GMT
< X-Server: webr02
< Expires: Tue, 06 Apr 2021 05:48:44 GMT
< Pragma:
< Transfer-Encoding: chunked
< Connection: Keep-Alive
< Last-modified: Tue, 06 Apr 2021 05:33:45 GMT
< X-Cache-Info: cached
< Age: 516
<
{ [945 bytes data]
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" media="screen" href="http://www.kakadu.de/themes/dradio/podcast/podcast.xsl"?><rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
...
```

**Comment by lukas-at-harren** [comment]
Closing this issue, as I was on an older version, and with `0.6.2` it got fixed.

**Comment by lukas-at-harren** [comment]
Nope, I was wrong. The issue persists. I am now on `0.6.3`.

**Comment by wojtekmach** [comment]
> ```
> {"content-encoding", "gzip"},
> ...
> <<31, 139, ...>
> ```

Your response has headers and body indicating gzip content (magic numbers `0x1f, 0x8b`) and Finch does not automatically decompress the response (https://github.com/keathley/finch/issues/129).

Curiously when I tried making the same request it was not compressed, maybe there was a CDN or proxy in front of your request? (I tried: `Finch.start_link(name: MyFinch); Finch.build(:get, "http://www.kakadu.de/podcast-kakadu.2730.de.podcast.xml") |> Finch.request(MyFinch)`.)

Do `:zlib.gunzip(response.body)` and you'll be good to go.

**Comment by sneako** [comment]
@wojtekmach is correct, as usual! In one project where I include "accept-encoding: gzip" in my request headers, and therefore expect that the response may be gzipped, I call the following function on the response body and it has been working well for me (note the magic bytes that Wojtek mentioned):
```
  defp decompress(<<31, 139, 8, _::binary()>> = body), do: :zlib.gunzip(body)
  defp decompress(not_compressed), do: not_compressed
```

I am not sure if Finch should do this automatically, but regardless that discussion will take place in #129 

I am going to close this issue, but feel free to chime in on #129, thanks!

**Comment by lukas-at-harren** [comment]
Hi @whatyouhide, @sneako thanks for having a look into it.
I actually just learned that content encoding is not handled by this library.
What I did is to take the advise from https://bernheisel.com/blog/httpoison-and-decompression to implement by own decompression on these responses.

I honestly think this should be implemented behaviour in the HTTP client (configurable of course), as it is with other clients like Tesla.

**Comment by keathley** [comment]
If we were going to support decompression we would need to support the other content-encodings beyond just gzip. That opens us up to a lot of potential maintenance costs because we'll need to evaluate whether there is a library to support each of these use schemes or if we'll need to re-implement it ourselves, etc. Supporting decompression also implies that we would need to support compression as well.

Also worth noting that this is only a useful feature if you're using the request function and doesn't help you if you're managing streaming on your own (since the caller is in control of how the accumulation is done).

I'm not _against_ this feature eventually making it into Finch. But we would need to figure out how to strike the right balance between performance trade-offs and ease of use for the user.
