### ISSUE TITLE
Including helpers for multipart requests

### ISSUE THREAD

**Issue by tomtaylor** [keathley/finch#131]
Hi there - I'm need to build and make streaming multipart requests, and noticed that Finch doesn't have support for this out of the box. Is this something I could contribute, or is this considered beyond the scope of the library and a separate dependency would be more appropriate?

Thanks!

**Comment by ijunaid8989** [comment]
you can use the module from Tesla https://github.com/teamon/tesla/blob/master/lib/tesla/multipart.ex

and can do something like this

```elixir
  def post(url, file_path, image) do
    multipart =
      Multipart.new()
      |> Multipart.add_file_content(image, file_path, headers: [{"content-type", "image/jpeg"}])

    headers = Multipart.headers(multipart)
    body = Multipart.body(multipart)

    EvercamFinch.request(
      :post,
      url,
      headers,
      {:stream, body}
    )
  end
```

**Comment by tomtaylor** [comment]
Thanks @ijunaid8989. I actually ended up using that as inspiration, but building a new library to support this functionality. Hopefully it's useful for someone else in the future:

https://github.com/breakroom/multipart

I'll go ahead and close this now.
