### ISSUE TITLE
Need to URI.encode the url - is it expected?

### ISSUE THREAD

**Issue by thbar** [keathley/finch#137]
First thanks for the great work on Finch, which we use as an easy streamer to compute checksums on remote resources (https://github.com/etalab/transport-site/blob/master/apps/shared/lib/http_stream_v2.ex), and more use will likely come. So, thanks!

While doing integration work, we noticed that doing a query against an url with `|` in it will fail:

```elixir
url = "http://tsvc2.pilote3.cityway.fr/api/Export/v1/GetExportedDataFile?ExportFormat=Gtfs&OperatorCode=AIXENBUS|CG13|CPA|ACCM|FRIOUL|AGGLOBUS|ETANG|COTEBLEUE|MARCOULINE|CIGALES|BUSDESCOLLINES|LIBEBUS|MILSAB|RTMNAV|RTM|SANPROVENCE"

{:error,
 %Mint.HTTPError{
   module: Mint.HTTP1,
   reason: {:invalid_request_target, ...}
```

(as I discovered by digging into the code, the error is coming from Mint, which does validation etc)

If we modify the url by encoding it from our side, the same query works:

```elixir
Finch.build(:head, URI.encode(url)) |> Finch.request(MyFinch)
{:ok, ...
```

What caught us a bit by surprise is that coming from `HTTPoison`, this is handled by default.

I'm not saying it is a good idea to support this by default of course (I much prefer letting the caller keep the control), but I could not find a mention of that caveat (if confirmed) in the documentation.

Do you think it would be worth adding a documentation note on that?

Thanks!

**Comment by sneako** [comment]
Hi @thbar and thanks for the kind words! 

Are you sure that HTTPoison is actually handling anything here? I assume it is rather the opposite, HTTPoison does not perform the validations that Mint is performing, but I have not taken a closer look to confirm this so I could be wrong.

I found many resources about what characters need to be encoded when I searched, but here is one of the more succinct examples that lists which characters are allowed in a URL and which ones should always be URL encoded https://developers.google.com/maps/documentation/urls/url-encoding

It mentions `|` several times as an example of a character that must be encoded. 

I'm not completely opposed to adding a note about this to Finch's docs, but there are probably many parts of the HTTP spec that aren't obvious to many developers and I'm not sure that Finch's documentation is the place to go over all of them. What do you think?
