### ISSUE TITLE
Memory pressure caused by connections removed from a pool

### ISSUE THREAD

**Issue by ono** [keathley/finch#140]
When a checkout fails because it exceeds `max_idle_time` Finch removes the connection from the pool. However it doesn't look to be closing the connection.

https://github.com/keathley/finch/blob/main/lib/finch/http1/pool.ex#L88-L98

The socket would be kept open until it's closed by the server. This can cause a big memory pressure under the high load.

I am happy to open a PR that fixes the issue but I thought I would check if that was intentional. Are there any reasons Finch doesn't close these connections?

**Comment by sneako** [comment]
Hi @ono ! Did you actually observe this behaviour happening or was this based on an assumption from reading the code? When we return `{:remove, :closed, pool_state}`, that tells NimblePool to remove the worker, which then will call the [terminate_worker/3](https://github.com/keathley/finch/blob/main/lib/finch/http1/pool.ex#L133) callback, which does try to close the connection.

**Comment by ono** [comment]
Oh, I see. I didn't notice how these are wired. Tested and confirmed that terminate_worker/3 was called and the socket was closed properly. The memory increase I am seeing must be caused by somewhere else. Thank you very much for your advise!
