### ISSUE TITLE
Not all errors returned by request/3 are Mint.Types.error()

### ISSUE THREAD

**Issue by lukebakken** [keathley/finch#142]
This may be related to #54 

We've noticed that some errors, like `:disconnected`, aren't "real" error types and can cause a `FunctionClauseError` when `Exception.message` is called on them.

See this branch for a demonstration:

https://github.com/lukebakken/finch/blob/some-errors-are-not-exceptions/test/finch/http2/pool_test.exs#L113-L155

See this issue for where we originally thought we should report it:

https://github.com/teamon/tesla/issues/469

It seems like this type spec should be updated, or the "non-Exception" errors be wrapped:

https://github.com/keathley/finch/blob/main/lib/finch.ex#L226-L227

Thanks a lot!

**Comment by sneako** [comment]
Hi @lukebakken and thanks for pointing this out. It looks like these errors are only happening with HTTP/2, right? I agree that we should update the type spec, or wrap the errors. I think it would be confusing to wrap these errors in Mint error structs, but I think we should stick with this pattern of returning error structs, so maybe it is time to introduce a %Finch.Error{}.

**Comment by lukebakken** [comment]
Hi @sneako. I only use HTTP/2 with this library so I can't speak to the HTTP case.

I'd be happy to work on adding `%Finch.Error{}`.

**Comment by lukebakken** [comment]
@keathley will the changes in #143 be shipping in version `0.8.0`?

**Comment by keathley** [comment]
@lukebakken Yup

**Comment by lukebakken** [comment]
Thanks! I'll keep my eyes out.

**Comment by keathley** [comment]
@lukebakken Published
