### ISSUE TITLE
HTTP monitor leak

### ISSUE THREAD

**Issue by NeilMenne** [keathley/finch#150]
While charting memory utilization in a service at B/R, I noticed that Finch was prominently in the top spot in the `:observer_cli`, so I confirmed my hypothesis that the memory was increasing overall.

Looking at, `:recon.info(pid) |> get_in([:signals, :monitored_by]) |> length()` we see that the monitors are increasing seemingly per-request. Since my requests are being made my `GenServer`s maintaining a cache, the processes they get linked to are long-lived.

@keathley helped me confirm diagnosis against the Finch code, so he should be able to help resolve this in a timely manner.

**Comment by keathley** [comment]
This should now be resolved with 0.8.2. Re-open if you continue to see issues.
