### ISSUE TITLE
Exponential backoff test is flaky

### ISSUE THREAD

**Issue by QuinnWilton** [keathley/finch#22]
On master (rarely):

```
  1) test request/5 will exponentially backoff until connection succeeds (FinchTest)
     test/finch_test.exs:205
     Assertion with >= failed
     code:  assert interval >= initial_backoff
     left:  35
     right: 37
     stacktrace:
       test/finch_test.exs:265: anonymous fn/3 in FinchTest."test request/5 will exponentially backoff until connection succeeds"/1
       (elixir 1.10.1) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir 1.10.1) lib/enum.ex:783: Enum.each/2
       test/finch_test.exs:262: (test)
```

**Comment by keathley** [comment]
I think we'll probably have to add some padding to that test, or find a way to make it deterministic (controlling the clock for instance)

**Comment by wojtekmach** [comment]
Alternatively I'd consider just testing the number of reconnections (which should give us confidence we're using backoff correctly) and not _when_ the reconnections happen - we assume that backoff does the right thing. On the flip side that would give us _less_ confidence in the system overall so it's definitely a tradeoff.

**Comment by QuinnWilton** [comment]
I haven't looked into the issue in much detail, but is it possible that the issue is just that `backoff:rand_increment/2` explicitly allows for backoffs that are shorter than the previous backoff?

Here's the implementation: https://github.com/ferd/backoff/blob/master/src/backoff.erl#L42

I think we might be able to just check that the new backoff falls within that range.

**Comment by wojtekmach** [comment]
it doesn't look like it can be shorter than the previous value but can be the same:

```elixir
iex> Stream.iterate(1, &:backoff.rand_increment(&1)) |> Enum.take(15)
[1, 1, 1, 1, 2, 3, 5, 5, 6, 7, 12, 33, 90, 132, 305]
```

**Comment by QuinnWilton** [comment]
It can only happen with `:backoff.rand_increment/2`, when the max delay is "close" to the current delay.

Using possible numbers from the test:
```
iex(10)> Stream.iterate(50, &:backoff.rand_increment(&1, 100)) |> Enum.take(100) |> IO.inspect(charlists: :as_lists)
[50, 46, 96, 76, 42, 94, 49, 37, 54, 58, 97, 72, 83, 69, 55, 37, 50, 93, 87, 76,
 84, 77, 78, 75, 41, 51, 50, 78, 51, 95, 42, 64, 51, 63, 82, 56, 57, 77, 43, 67,
 88, 84, 92, 53, 58, 80, 66, 77, 94, 42, ...]
```

So just adjusting the backoff arguments can likely lead to more stable results, I think.
