### ISSUE TITLE
Finch times out when attempting to connect to a bad address

### ISSUE THREAD

**Issue by mhanberg** [keathley/finch#23]
Currently when Finch attempts to connect to a server that doesn't exist/is down, it will time out instead of raising/throwing/returning an error stating that it can't connect.

I came across this when attempting to swap out HTTPoison with Finch in the [Wallaby](https://github.com/elixir-wallaby/wallaby) project.
![image](https://user-images.githubusercontent.com/5523984/79076630-a9f68e80-7cc9-11ea-9437-8b718f778d5a.png)

I think other HTTP clients will usually use an error along the lines of `:econnrefused` or `:nxdomain` for the corresponding connection errors.

**Comment by mhanberg** [comment]
Might want to surface some some Mint.TransportErrors [here](https://github.com/keathley/finch/blob/master/lib/finch/conn.ex#L47).

**Comment by keathley** [comment]
I think that might make sense. If we get an nxdomain error back there's probably not a lot we can do about that and should probably return that as an error to the client.

**Comment by mhanberg** [comment]
At least concerning the transport errors, I think `:timeout`, might be the only one worth retrying.

**Comment by keathley** [comment]
The current issue is that if we can't get a valid connection process from the pool, the pool will spin through all of the connections to try to find one that's valid. In the case where the service we're trying to communicate with is down, the pool will try to find a valid connection until the timeout is reached.

I think we'll have to update how we checkout a connection from the pool. We can either return a connection or an error. If we return an error the error can be surfaced to the caller. If we return a valid connection then the caller process will attempt to execute the request.
