### ISSUE TITLE
First Use Time & Idle Time Tracking

### ISSUE THREAD

**Issue by sneako** [keathley/finch#27]
This will help in configuring pool size & count.

We can record System.monotonic_time on init and handle_checkin and subtract it from System.monotonic_time on handle_checkout.

Since init doesn't connect, maybe "first_use_time" makes sense as the name for that measurement.

**Comment by keathley** [comment]
Just so I'm clear, what we're trying to determine is how often a pool or a connection in that pool, is being used. Is my understanding correct?

**Comment by sneako** [comment]
Yeah, I want to be able to figure out how long a connection is sitting in the pool between check outs
