### ISSUE TITLE
Emit telemetry events

### ISSUE THREAD

**Issue by keathley** [keathley/finch#4]
Finch should support telemetry events around requests. It probably makes sense to follow the new `span` conventions.

Here are the metrics that we tend to use when diagnosing production issues:

* queue duration
* new connection duration
* request duration
* response duration
* rate of new connections vs rate of reused connection

I think all of the durations we can get "for free" using spans.

**Comment by sneako** [comment]
For reference, here is the discussion around telemetry spans https://github.com/beam-telemetry/telemetry/issues/57

**Comment by keathley** [comment]
I'm going to start working on this tonight.
