### ISSUE TITLE
Support arbitrary string methods

### ISSUE THREAD

**Issue by sneako** [keathley/finch#40]
Right now, we currently have guard clauses that are perhaps a bit too restrictive and therefore do not allow the user to use arbitrary HTTP methods.

Are there any good reasons to keep this limitation, or should it be removed?

**Comment by whatyouhide** [comment]
The HTTP spec only specifies a _semantic meaning_ for the well-known methods (GET, POST, and so on), but it doesn't restrict the *supported* methods to those. WebDAV for example uses custom methods. I don't think there's any reason to restrict those. :)

**Comment by sneako** [comment]
Thanks for the insight @whatyouhide I agree! Working on this now so I can update #39 accordingly.
