### ISSUE TITLE
accept %URI{} as well as binary for url()

### ISSUE THREAD

**Issue by supersimple** [keathley/finch#46]
https://hexdocs.pm/finch/Finch.html#t:url/0 defines a url as a binary(). I am accustomed to passing around %URI{} structs instead.

Is there a reason you wouldn't also accept (or perhaps only expect) a %URI{} struct?

BTW - love the library, just thought I'd ask.

**Comment by wojtekmach** [comment]
I think allowing %URI{} makes sense. We call URI.parse/1 under the hood anyway so if we happen to have the uri struct already, we'd avoid overhead of parsing it inside request.

**Comment by sneako** [comment]
Sounds good to me! I like the idea of being able to skip the url parsing

**Comment by supersimple** [comment]
I opened up https://github.com/keathley/finch/pull/47
