### ISSUE TITLE
Handling timeout and error with Finch 

### ISSUE THREAD

**Issue by NidalShater** [keathley/finch#56]
In HTTPPoison
 ```
headers=[{"Content-Type", "application/json"},timeout: @timeout, recv_timeout: @timeout]
case HTTPoison.post(url,P%{},headers, hackney: [pool: :first_pool]) do
       {:ok, %{status_code: status, body: data}} -> 
           ...........
       {:error, %HTTPoison.Error{reason: reason}} ->
           ............ 
```
how can we deal with timeout or how to handle error in Finch?

I tried the following to handle Error 
```
case Finch.request(MyFinch, :get, "https://api.github.com/zen") do
      {:ok, %{status: status, body: data}} -> 
        IO.inspect status
        IO.inspect data
      {:error, %Finch.Error{reason: reason}} ->
        IO.inspect error
    end
```
but I get the following error :

`Finch.Error.__struct__/0 is undefined, cannot expand struct Finch.Error. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code`

and try to handle the header using this code
```
headers=[{"Content-Type", "application/json"},timeout: @timeout, recv_timeout: @timeout]
    case Finch.request(MyFinch, :post, url, headers,Poison.encode!(%{})) do
```
but it didn't work

**Comment by sneako** [comment]
Thanks for trying out Finch! 

As you have discovered, Finch is not meant to be a drop in replacement for HTTPoison. At this time Finch is returning errors directly from Mint, however we have begun planning to wrap errors in our own Finch.Error struct in #54. Mint is still pre 1.0, so everything is potentially subject to change :)

Your example should work if you just remove the reference to `Finch.Error` and just match on `{:error, %{reason: reason}}` instead.
