### ISSUE TITLE
Allow custom pool assignment other than {scheme, host, port}

### ISSUE THREAD

**Issue by chulkilee** [keathley/finch#57]
If pool is only determined by `{scheme, host, port}`, then SSL option will not be considered, which results in mixing up connection with different SSL option. (e.g. using SSL client side certificate for authentication)

### Related

- https://elixirforum.com/t/strange-httpc-hackeny-behavior-on-ssl-verify/22695/3
- https://github.com/benoitc/hackney/issues/570

**Comment by josevalim** [comment]
Can you please explain how this is possible? Finch connection parameters cannot be given dynamically, you need to specify them when you specify the schema+host+port, so I don't see how you would end-up with a mixed state.

**Comment by chulkilee** [comment]
Oh, I see - connection option can only be given to `Finch.HTTP1.Pool.start_link/1`, not per request.

I thought that can be given to `opts` on `Finch.request/4`, but it's not.

Thanks!
