### ISSUE TITLE
Allow pool configuration urls to be provided as a binary?

### ISSUE THREAD

**Issue by sneako** [keathley/finch#7]
Right now we force the user to mentally parse the url in to the `{scheme, host, port}` (not that it's very difficult), but maybe some users would prefer to configure their pools like:
```
pools: %{
  "https://hex.pm" => %{size: 10, count: 2}
}
```
instead of the current:
```
pools: %{
  {:https, "hex.pm", 443} => %{size: 10, count: 2}
}
```

**Comment by keathley** [comment]
I think this is reasonable. It makes it a lot easier to configure at runtime when you might not know all of this information before the app boots.

**Comment by QuinnWilton** [comment]
To clarify, do you want to support both ways of configuring the URL, or are you intending to switch wholesale to passing in a binary?

**Comment by sneako** [comment]
Good question! I was originally thinking of supporting both, but maybe we should only allow the binary?

**Comment by sneako** [comment]
What do you think @keathley? I'm leaning towards only allowing the binary.

**Comment by keathley** [comment]
I'm fine with limiting this to only binaries. It makes the logic simpler and seems less error-prone.

**Comment by QuinnWilton** [comment]
I'm working on this one right now!

**Comment by QuinnWilton** [comment]
Actually, I have this implemented, but because it relies on processing and validating the `config` that is passed to `Finch.PoolManager`, it overlaps with @sneako's PR a little bit: https://github.com/keathley/finch/pull/19/files

It might be best if I hold off until that gets merged, and then apply my changes on top.

My diff (minus my tests) is the following:

```elixir
+++ b/lib/finch/pool_manager.ex
@@ -8,10 +8,17 @@ defmodule Finch.PoolManager do
 
   @impl true
   def init(config) do
+    config = process_and_validate_config(config)
+
     Enum.each(config.pools, fn
-      {:default, _} -> :ok
-      {shp, _} -> do_start_pools(shp, config)
-      _ -> :ok
+      {:default, _} ->
+        :ok
+
+      {shp, _} ->
+        do_start_pools(shp, config)
+
+      _ ->
+        :ok
     end)
 
     {:ok, config}
@@ -53,6 +60,31 @@ defmodule Finch.PoolManager do
     {:reply, reply, state}
   end
 
+  defp process_and_validate_config(config) do
+    pools =
+      Map.new(config.pools, fn
+        {url, pool_config} when is_binary(url) ->
+          {url_to_shp(url), pool_config}
+
+        pool ->
+          pool
+      end)
+
+    Map.put(config, :pools, pools)
+  end
+
+  defp url_to_shp(url) when is_binary(url) do
+    case URI.parse(url) do
+      %{scheme: scheme, host: host, port: port}
+      when is_binary(scheme) and is_binary(host) and is_integer(port) and
+             scheme in ["http", "https"] ->
+        {String.to_existing_atom(scheme), host, port}
+
+      _ ->
+        raise ArgumentError, "Invalid url=(#{url})"
+    end
+  end
```

But I think the validation logic can be cleaned up a ton if I leverage the work Nico has already done.

**Comment by sneako** [comment]
I was thinking that we should do all of the validations in the public interface Finch module, that way we know we are working with valid data everywhere else. We already do parsing of URLs in to {s, h, p} in [Finch.request/5 function](https://github.com/keathley/finch/blob/master/lib/finch.ex#L103) so we should probably extract that functionality in to it's own function so we can continue to use it there, and also when we are handling the pool config. What do you think? I agree it makes sense to wait for  #19 to be merged for the reasons you mentioned :)

**Comment by QuinnWilton** [comment]
> I was thinking that we should do all of the validations in the public interface Finch module

I agree! I think that the work you've done in #19 lays some really great groundwork for this sort of validation logic.

> We already do parsing of URLs in to {s, h, p} in Finch.request/5 function so we should probably extract that functionality in to it's own function

That sounds like a good plan! I wasn't super happy with my URL validation, but if we just want to mirror the parsing we do in `Finch.request/5`, then that simplifies things a ton. Is it alright then to have a `nil` port in the `shp` tuple?

**Comment by sneako** [comment]
The port should never be nil. `URI.parse/1` should give us the port based on the scheme

**Comment by QuinnWilton** [comment]
Oh, so it does! That makes things easy then.
