### ISSUE TITLE
Non-string values in headers cause a Mint exception 

### ISSUE THREAD

**Issue by ashutoshrishi** [keathley/finch#82]
I noticed this when trying to use Finch as an `:ex_aws` client adapter where the `{"content-length", 0}` headers (and like) cause a crash. 

The exact same issue with Mojito: https://github.com/appcues/mojito/issues/46

The issue was opened in Mint too: https://github.com/elixir-mint/mint/issues/235

Mint decided to leave it to the wrapping implementations has they clearly expect a string. Mojito decided to serialise their header values recursively. 

For now I am doing exactly what Mojito is doing but in my own `:ex_aws` client adapter code.

**Comment by visciang** [comment]
@ashutoshrishi I've had the same issue.
Check my PR here https://github.com/ex-aws/ex_aws/pull/710, merged but bot jet published a new version of the library

**Comment by keathley** [comment]
I guess I'm a little confused...isn't the issue here in ex_aws? We're just passing headers on to mint, so it seems like trying to intervene on the user's behalf is the wrong approach. But maybe I'm wrong?

**Comment by visciang** [comment]
Yes, you're right, the bug is in ex_aws. My PR ex_aws side fix the issue.

**Comment by keathley** [comment]
Ok, cool. Thanks for that :). I'm going to close this since I don't think there's much to do here and I don't think we want to spend additional CPU cycles checking every header for every request. If you feel like I've missed something, feel free to re-open.
