### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by myi2000** [keathley/finch#85]
Hello,
Need help, can't get the proxy working.  Tried setting conn_opts, that is supposed to pass to Mint.HTTP.connect/4.
conn_opts: [proxy: [:http, proxyurl, proxyport, []]]

**Comment by keathley** [comment]
You need to pass a tuple like so: `conn_opts: [proxy: {:http, proxyurl, proxyport, []}]`.

**Comment by myi2000** [comment]
@Keathley, thanks for quick response.  I tried but it doesnt use the proxy, example below, appreciate your input.  Thanks.

defmodule T1 do
  alias Finch.Response

  def proxy do
    proxyurl = "24.185.57.132"
    proxyport = "3126"
    url = "https://www.webpagetest.org/"
    Finch.start_link(
      name: MyFinch,
      pools: %{ :default => [size: 5], url => [size: 5] },
      conn_opts: [proxy: {:http, proxyurl, proxyport, []}]
    )
    Finch.build(:get, url) |> Finch.request(MyFinch) |> handle_response
  end

  defp handle_response({:ok, %Response{body: body}}) do
    IO.puts("handle_response")
    IO.puts(body)
  end

  defp handle_response({:error, body}) do
    IO.puts("error_response")
    IO.puts(body)
  end
end

**Comment by sneako** [comment]
@myi2000 have you tried providing the proxyport value as an integer?

**Comment by myi2000** [comment]
@sneako, thanks.  Yes, I tried with, 
proxyport = 3126

that dint work either.
It seems that conn_opts is being ignored.

**Comment by sneako** [comment]
Ah sorry, I just took a quick glance before, the conn_opts should be passed inside the pool config, like:
```
pools: %{
  :default => [
    size: 5, 
    conn_opts: [proxy: {:http, proxyurl, proxyport, []}]
  ]
}
```

**Comment by myi2000** [comment]
@sneako, it works, thanks for quick help.

note: if pools defines url, then each should have its own conn_opts section.
