### ISSUE TITLE
Proxying a HTTP/1 connection

### ISSUE THREAD

**Issue by adriankumpf** [keathley/finch#90]
I tried to configure proxying but could not get it to work. While I was digging into the code, I noticed that both pool implementations use the `connect/4` function specific to the HTTP protocol version. According to the docs [Mint.HTTP1.connect/4](https://hexdocs.pm/mint/Mint.HTTP1.html#connect/4) "[…] doesn't support proxying" though. The `:proxy` configuration seems to be supported by [`Mint.HTTP.connect/4`](https://github.com/elixir-mint/mint/blob/v1.2.0/lib/mint/http.ex#L339) only.

Am I missing something? Has anyone successfully set up proxying?

**Example code:**

```elixir
pools: %{
  :default => [size: 5, conn_opts: [proxy: {:http, proxy_url, proxy_port, []}]]
}
```

**Comment by keathley** [comment]
This might be a bug in how finch uses `connect`. I wasn't aware that you couldn't use proxy through the direct `HTTP1.connect` call. I can take a look at this.

**Comment by keathley** [comment]
@adriankumpf Can you try this PR and see if that fixes your issue: https://github.com/keathley/finch/pull/91? Also, if you happen to have a failing test case for this, that would be rad :).

**Comment by adriankumpf** [comment]
Thank you for the quick fix! So far it looks very good. I have not noticed any problems. Unfortunately I have no failing test for this, everything was tested manually.
